/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlanificadorRouteImport } from './routes/planificador'
import { Route as ObjetivosRouteImport } from './routes/objetivos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as ContenidoRouteImport } from './routes/contenido'
import { Route as CampanasRouteImport } from './routes/campanas'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as IndexRouteImport } from './routes/index'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanificadorRoute = PlanificadorRouteImport.update({
  id: '/planificador',
  path: '/planificador',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetivosRoute = ObjetivosRouteImport.update({
  id: '/objetivos',
  path: '/objetivos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContenidoRoute = ContenidoRouteImport.update({
  id: '/contenido',
  path: '/contenido',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanasRoute = CampanasRouteImport.update({
  id: '/campanas',
  path: '/campanas',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/campanas': typeof CampanasRoute
  '/contenido': typeof ContenidoRoute
  '/equipo': typeof EquipoRoute
  '/ideas': typeof IdeasRoute
  '/login': typeof LoginRoute
  '/objetivos': typeof ObjetivosRoute
  '/planificador': typeof PlanificadorRoute
  '/pricing': typeof PricingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/campanas': typeof CampanasRoute
  '/contenido': typeof ContenidoRoute
  '/equipo': typeof EquipoRoute
  '/ideas': typeof IdeasRoute
  '/login': typeof LoginRoute
  '/objetivos': typeof ObjetivosRoute
  '/planificador': typeof PlanificadorRoute
  '/pricing': typeof PricingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/campanas': typeof CampanasRoute
  '/contenido': typeof ContenidoRoute
  '/equipo': typeof EquipoRoute
  '/ideas': typeof IdeasRoute
  '/login': typeof LoginRoute
  '/objetivos': typeof ObjetivosRoute
  '/planificador': typeof PlanificadorRoute
  '/pricing': typeof PricingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/campanas'
    | '/contenido'
    | '/equipo'
    | '/ideas'
    | '/login'
    | '/objetivos'
    | '/planificador'
    | '/pricing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/campanas'
    | '/contenido'
    | '/equipo'
    | '/ideas'
    | '/login'
    | '/objetivos'
    | '/planificador'
    | '/pricing'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/campanas'
    | '/contenido'
    | '/equipo'
    | '/ideas'
    | '/login'
    | '/objetivos'
    | '/planificador'
    | '/pricing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CampanasRoute: typeof CampanasRoute
  ContenidoRoute: typeof ContenidoRoute
  EquipoRoute: typeof EquipoRoute
  IdeasRoute: typeof IdeasRoute
  LoginRoute: typeof LoginRoute
  ObjetivosRoute: typeof ObjetivosRoute
  PlanificadorRoute: typeof PlanificadorRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planificador': {
      id: '/planificador'
      path: '/planificador'
      fullPath: '/planificador'
      preLoaderRoute: typeof PlanificadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetivos': {
      id: '/objetivos'
      path: '/objetivos'
      fullPath: '/objetivos'
      preLoaderRoute: typeof ObjetivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contenido': {
      id: '/contenido'
      path: '/contenido'
      fullPath: '/contenido'
      preLoaderRoute: typeof ContenidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanas': {
      id: '/campanas'
      path: '/campanas'
      fullPath: '/campanas'
      preLoaderRoute: typeof CampanasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  CampanasRoute: CampanasRoute,
  ContenidoRoute: ContenidoRoute,
  EquipoRoute: EquipoRoute,
  IdeasRoute: IdeasRoute,
  LoginRoute: LoginRoute,
  ObjetivosRoute: ObjetivosRoute,
  PlanificadorRoute: PlanificadorRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
